#! VARS:
#! PROVIDER_NAME
#! SUBNET_NAME
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ${PROVIDER_NAME}
  namespace: default
  labels:
    network.harvesterhci.io/clusternetwork: mgmt
    network.harvesterhci.io/type: OverlayNetwork
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"${PROVIDER_NAME}","type":"kube-ovn","provider":"${PROVIDER_NAME}.default.ovn","server_socket":"/run/openvswitch/kube-ovn-daemon.sock"}
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ${SUBNET_NAME}
spec:
  cidrBlock: 10.20.0.0/24
  default: false
  enableLb: true
  excludeIps:
    - 10.20.0.1
  gateway: 10.20.0.1
  gatewayNode: ''
  gatewayType: distributed
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ${PROVIDER_NAME}.default.ovn
  vpc: ovn-cluster